language: node_js
node_js: 10
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: test
      script:
        - npm run test
        - npm run test:mutate
    - stage: build
      script:
        - npm run prepublishOnly
